apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    app: curl
spec:
  selector:
    matchLabels:
      app: curl
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      volumes:
      containers:
      - name: curl
        image: radial/busyboxplus:curl
        command:
        - sh
        - -c
        - while true; do sleep 1; done
